// import styles from "./page.module.css";
import { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Home Page",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <>
      <div> hello world</div>
      <Link href="register">register</Link>
    </>
  );
}
